# Generated by Django 6.0.3 on 2026-08-20 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.TextField(unique=True)),
                ('nome', models.TextField()),
                ('endereco', models.TextField()),
                ('horario_resumo', models.TextField(null=True)),
                ('whatsapp_contato', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('whatsapp', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('foto_url', models.TextField(null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('papel', models.CharField(choices=[('DONO', 'Dono'), ('BARBEIRO', 'Barbeiro')], default='BARBEIRO', max_length=20)),
                ('senha_hash', models.TextField(null=True)),
                ('token_version', models.IntegerField(default=0)),
                ('convite_token_hash', models.TextField(null=True)),
                ('convite_expira_em', models.DateTimeField(null=True)),
                ('tentativas_login', models.IntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(null=True)),
                ('desativado_em', models.DateTimeField(null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='barbeiros', to='tenant.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('ALMOCO', 'Almoco'), ('FOLGA', 'Folga'), ('PESSOAL', 'Pessoal'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('repete_semanalmente', models.BooleanField()),
                ('dia_semana', models.IntegerField(null=True)),
                ('minutos_inicio', models.IntegerField(null=True)),
                ('minutos_fim', models.IntegerField(null=True)),
                ('inicio', models.DateTimeField(null=True)),
                ('fim', models.DateTimeField(null=True)),
                ('observacao', models.TextField(null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bloqueios', to='tenant.barbearia')),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='tenant.barbeiro')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('whatsapp', models.TextField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clientes', to='tenant.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField()),
                ('minutos_inicio', models.IntegerField()),
                ('minutos_fim', models.IntegerField()),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='horarios', to='tenant.barbearia')),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='tenant.barbeiro')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('duracao_minima_min', models.IntegerField()),
                ('duracao_sugerida_min', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='servicos', to='tenant.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='BarbeiroServico',
            fields=[
                ('pk', models.CompositePrimaryKey('barbeiro', 'servico', blank=True, editable=False, primary_key=True, serialize=False)),
                ('duracao_min', models.IntegerField()),
                ('preco_centavos', models.IntegerField(null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='barbeiro_servicos', to='tenant.barbearia')),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='tenant.barbeiro')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vinculos', to='tenant.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.TextField(unique=True)),
                ('servico_nome', models.TextField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('duracao_min', models.IntegerField()),
                ('preco_centavos', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO_CLIENTE', 'Cancelado Cliente'), ('CANCELADO_BARBEIRO', 'Cancelado Barbeiro')], default='CONFIRMADO', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelado_em', models.DateTimeField(null=True)),
                ('lembrete_enviado_em', models.DateTimeField(null=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendamentos', to='tenant.barbearia')),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendamentos', to='tenant.barbeiro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendamentos', to='tenant.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendamentos', to='tenant.servico')),
            ],
        ),
        migrations.AddConstraint(
            model_name='barbeiro',
            constraint=models.UniqueConstraint(fields=('barbearia', 'whatsapp'), name='barbeiro_whatsapp_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='barbeiro',
            constraint=models.UniqueConstraint(fields=('barbearia', 'id'), name='barbeiro_id_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('barbearia', 'whatsapp'), name='cliente_whatsapp_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('barbearia', 'id'), name='cliente_id_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='horariotrabalho',
            constraint=models.UniqueConstraint(fields=('barbeiro', 'dia_semana'), name='jornada_unica_por_dia'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.UniqueConstraint(fields=('barbearia', 'nome'), name='servico_nome_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.UniqueConstraint(fields=('barbearia', 'id'), name='servico_id_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['barbeiro', 'inicio'], name='agendamento_barbeiro_dia'),
        ),
    ]
