# Generated by Django 6.0.3 on 2026-08-20 13:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_admin_grants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login', models.TextField(unique=True)),
                ('papel', models.CharField(choices=[('ADMIN', 'Admin'), ('DONO', 'Dono'), ('BARBEIRO', 'Barbeiro')], max_length=20)),
                ('senha_hash', models.TextField(null=True)),
                ('token_version', models.IntegerField(default=0)),
                ('convite_token_hash', models.TextField(null=True)),
                ('convite_expira_em', models.DateTimeField(null=True)),
                ('tentativas_login', models.IntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('desativado_em', models.DateTimeField(null=True)),
                ('barbearia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='tenant.barbearia')),
            ],
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='perfil', to='tenant.usuario'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('barbearia__isnull', True), ('papel', 'ADMIN')), models.Q(models.Q(('papel', 'ADMIN'), _negated=True), ('barbearia__isnull', False)), _connector='OR'), name='admin_sem_barbearia_resto_com'),
        ),
    ]
