# Generated by Django 6.0.3 on 2026-08-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_rls_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='bloqueado_ate',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='convite_expira_em',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='convite_token_hash',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='papel',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='senha_hash',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='tentativas_login',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='token_version',
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='perfil', to='tenant.usuario'),
        ),
    ]
