# Generated by Django 6.0.3 on 2026-10-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_whatsapp_central'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadodiaenviada',
            name='barbeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_enviadas', to='tenant.barbeiro'),
        ),
    ]
